# Generated by Django 3.2.5 on 2021-08-21 07:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_alter_cursos_lecciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
