# Generated by Django 3.2.4 on 2021-08-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_alter_cursos_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesores',
            name='email',
        ),
        migrations.AddField(
            model_name='profesores',
            name='username',
            field=models.TextField(null=True),
        ),
    ]
