# Generated by Django 3.2.4 on 2021-08-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0007_auto_20210822_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesores',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Clave Profesor'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Clave Usuario'),
        ),
    ]
