# Generated by Django 3.2.4 on 2021-08-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0008_auto_20210822_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='curso',
        ),
        migrations.AddField(
            model_name='usuario',
            name='curso',
            field=models.ManyToManyField(help_text='Seleccione los Cursos a cursar', to='registros.Cursos'),
        ),
    ]
