# Generated by Django 3.2.4 on 2021-08-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0009_auto_20210822_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='duracion',
            field=models.IntegerField(verbose_name='Duracion en Horas'),
        ),
    ]
