# Generated by Django 3.2.4 on 2021-08-23 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0011_auto_20210823_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='fecha_Inicio',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cursos',
            name='fecha_terminacion',
            field=models.DateField(null=True),
        ),
    ]
