# Generated by Django 3.2.4 on 2021-08-24 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0012_auto_20210823_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='fecha_Inicio',
            new_name='fecha_inicio',
        ),
    ]
