# Generated by Django 3.2.4 on 2021-08-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0013_rename_fecha_inicio_cursos_fecha_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave Usuario')),
                ('total', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Registro')),
                ('curso', models.ManyToManyField(help_text='Seleccione los Cursos a cursar', to='registros.Cursos')),
            ],
        ),
    ]
