# Generated by Django 3.2.4 on 2021-08-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0014_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='username',
            field=models.TextField(null=True),
        ),
    ]
