# Generated by Django 3.2.4 on 2021-08-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0015_carrito_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave Usuario')),
                ('correo', models.EmailField(max_length=254, null=True)),
                ('asunto', models.TextField(null=True)),
                ('mensaje', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Mensaje Contacto',
                'verbose_name_plural': 'Mensajes Contactos',
            },
        ),
        migrations.AlterModelOptions(
            name='carrito',
            options={'ordering': ['-created'], 'verbose_name': 'Carrito', 'verbose_name_plural': 'Carritos'},
        ),
        migrations.AlterField(
            model_name='cursos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id Curso'),
        ),
        migrations.AlterField(
            model_name='profesores',
            name='username',
            field=models.TextField(null=True, verbose_name='User Profesor'),
        ),
    ]
