# Generated by Django 3.2.5 on 2021-08-25 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0016_auto_20210824_1909'),
        ('registros', '0016_auto_20210824_1942'),
    ]

    operations = [
    ]
